on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Code Quality

jobs:
  quality:
    name: Check Code Quality
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install gtk3 and dependencies.
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxft-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxrender-dev \
            libxfixes-dev \
            libpango1.0-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libasound2-dev

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}