on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Linux CI

jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install audio dependency.
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxft-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxrender-dev \
            libxfixes-dev \
            libpango1.0-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libasound2-dev \
            libwayland-dev \
            libxkbcommon-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Check Code
        run: cargo check
          
      # NOTE: As of 01/29/22, GitHub Actions hangs on running a GUI test, as
      # if it's in an infinite loop, so this is disabled for the time
      # being.
      # - name: Run headless test
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: cargo test -- --test-threads=1
