# Used the following as reference:
# https://github.com/gtk-rs/gtk-rs-core/blob/master/.github/workflows/windows.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Windows CI

jobs:
  check:
    name: Compile and Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Check Code
        uses: actions-rs/cargo@v1
        with:
          command: check
          
      # NOTE: As of 01/29/22, GitHub Actions hangs on running a GUI test, as
      # if it's in an infinite loop, so this is disabled for the time
      # being.
      # - name: Run headless test
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: cargo test -- --test-threads=1
